services:
  caddy:
    image: caddy
    container_name: caddy
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - pocketbase
    networks:
      - internal
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pocketbase
    # ports:
    #   - '8080:8080'
    # environment:
    volumes:
      - pb_data:/pb/pb_data
      - ./pocketbase/pb_migrations:/pb/pb_migrations
      - ./pocketbase/pb_hooks:/pb/pb_hooks
    networks:
      - internal

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./docker-volume/minio-data:/data
    networks:
      - internal

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - '8025:8025'
      - '1025:1025'
    networks:
      - internal

volumes:
  pb_data:
  caddy_data:
  caddy_config:

networks:
  internal:
    driver: bridge